version: '2'

services:
  php-nginx:
    image: "webdevops/php-nginx-dev:ubuntu-16.04"
    ports:
      - "80:80"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
      # laravel WEB_DOCUMENT_ROOT is /app/public
    networks:
      - backend
  mysql:
    image: "mysql:5.7"
    volumes:
        - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: secret
    command: ['mysqld', '--character-set-server=utf8']
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend: